org: aacosta
app: typescript-reminder
service: typescript-reminder
frameworkVersion: '3'

custom:
  config:
    DYNAMODB_REMINDERS_T: ${ssm:REMINDER_TABLE}
    DYNAMODB_USERS_T: ${ssm:USERS_TABLE}

provider:
  name: aws
  runtime: nodejs14.x
  enviroment: ${self:custom.config}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Get*"
        - "dynamodb:Scan*"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-remindersTable-${sls:stage}
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Get*"
        - "dynamodb:Scan*"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-usersTable-${sls:stage}

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  createReminder:
    handler: handler.createReminder
    events:
      - httpApi:
          path: /create
          method: post
  createTest:
    handler: handler.createTest
    events:
      - httpApi:
          path: /createTest
          method: post
resources:
  Resources:
    RemindersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-remindersTable-${sls:stage}
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: email 
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:service}-usersTable-${sls:stage}


plugins:
  - serverless-plugin-typescript
